__title__ = 'convertio'
__description__ = 'An API wrapper for convertio.co'
__url__ = 'https:/github.com/PetitPotiron/python-convertio/'
__version__ = '1.1.2'
__author__ = 'PetitPotiron'
__license__ = 'GNU General Public License v3.0'
__copyright__ = 'Copyright (c) 2021 PetitPotiron'
